<template>
    <div class="container">
        <div class="title">Dashboard</div>
        <div class="dashboard-divider">
            <v-card class="card">
            <div class="heading">Student Information</div>
            <div class="divider">
                <div class="profilecontainer">
                    <div class="usertitle">{{ user["name"] }}</div>
                    <div class="userid"><b>Email:</b> {{ user["email"] }}</div>
                    <div class="userid"><b>Student ID:</b> {{ user["id"] }}</div>
                    <div class="userid">{{ user["description"] }}</div>
                </div>
                <div class="datacontainer">
                    <div class="profile">
                        <v-icon v-if="image == null">mdi-account</v-icon>
                        <img img class="imghandler" v-if="image != null" v-bind:src="image" cover></img>
                    </div>
                    <v-btn class="button" @click="signout">Sign Out</v-btn>
                </div>

            </div>
        </v-card>
        <v-card class="card">
            <div class="heading">Student Analytics</div>
            <div class="divider">
                <div class="profilecontainer">
                    <div class="usertitle">Study Details</div>
                    <div class="userid"><b>Total Quizes:</b>{{myData[0]}}</div>
                    <div class="userid"><b>Total Solved:</b>{{myData[1]}}</div>
                    <div class="userid"><b>Created By Me:</b>{{myData[2]}} </div>
                </div>
            </div>
        </v-card>
    </div>
    <div class="dashboard-divider">
        <div class="card2">
        <div class="dashboard-divider">
            <v-card class="welcome-label">
            <div class="heading">Library</div>
            <div class="text">Our Library includes Quizes which are generated by every user!</div>
            <div class="text">Happy Solving!</div>
            <div class="spacer"></div>
            <v-btn class="button2">Library</v-btn>
            </v-card>
            <v-card class="welcome-label">
            <div class="heading">Creator</div>
            <div class="text">Check out our AI Based Quiz Creator!! Powered by Generative AI!</div>
            <div class="text">More Features Coming Soon!</div>
            <div class="spacer"></div>
            <v-btn class="button2">Creator</v-btn>
            </v-card>
        </div>
        </div>
        <div class="card2">
        <div class="dashboard-divider">
            <v-card class="welcome-label">
                <div class="graphcontainer">
                    <Bar :data="chartData" :options="chartOptions" width="600" height="300" />
                </div>
            </v-card>
        </div>
        </div>
    </div>
    </div>

</template>

<script setup>
import { ref, onMounted, watch } from 'vue';
import { GETTOKEN, API, SETTOKEN, SETSTUDENT, GETSTUDENT } from '@/main';
import router from '../router';

import { Bar } from 'vue-chartjs'
import { Chart as ChartJS, Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale } from 'chart.js'
ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale)

const data = ref(null);
const myData = ref([0,0,0]);
const chartData = ref({
  labels: ['Total Solved', 'Total Quizes', 'Created by Me'],
  datasets: [{
    data: [1,1,0],
    backgroundColor: [
      'rgba(155, 155, 155, 0.2)',
      'rgba(232, 224, 255)',
      'rgba(155, 155, 155, 0.2)'
    ],
    borderColor: [
      'rgba(155, 155, 155, 1)',
      'rgba(150, 121, 237, 1)',
      'rgba(155, 155, 155, 1)'
    ],
    borderWidth: 1
  }]
});

const chartOptions = ref({
  responsive: true,
  plugins: {
    legend: {
      position: ''
    }
  }
});

const user = ref({name: "", email: "", id: "", description: "", image: null});

const requestAnalytics = async () => {
    console.log("Requesting Analytics")
    const response = await fetch(API + '/get/user/analytics', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + GETTOKEN()
        },
        body: JSON.stringify({
            studentid: GETSTUDENT().id
        })
    });

    const data = await response.json();
    console.log(data);

    if (data.status == 200) {
        console.log("Data Received")
        myData.value = [data.totalAttempts, data.totalQuizzesAll, data.totalQuizzes];
        chartData.value = {
            labels: ['Total Solved', 'Total Quizes', 'Created by Me'],
            datasets: [{
                data: [data.totalAttempts, data.totalQuizzesAll, data.totalQuizzes],
                backgroundColor: [
                    'rgba(155, 155, 155, 0.2)',
                    'rgba(232, 224, 255)',
                    'rgba(155, 155, 155, 0.2)'
                ],
                borderColor: [
                    'rgba(155, 155, 155, 1)',
                    'rgba(150, 121, 237, 1)',
                    'rgba(155, 155, 155, 1)'
                ],
                borderWidth: 1
            }]
        }
    }
}

const loading = ref(false);

const required = (v) => !!v || '';

const props = defineProps({
    page: Number
});

const signout = async () => {
    SETSTUDENT(null);
    SETTOKEN(null);
    router.push('/login');
}

watch(() => props.page, (value) => {
    if (!GETTOKEN()) router.push("/login");
    if (!GETSTUDENT()) router.push("/login");
    user.value = GETSTUDENT();
    if (!GETSTUDENT().hasOwnProperty("description")) user.value["description"] = "";
    if (!GETSTUDENT().hasOwnProperty("image")) user.value["image"] = null;
    image.value = user.value["image"];

    console.log(user.value);
    requestAnalytics();
});

const imgopen = ref(false);
const image = ref(null);
onMounted(() => {
    if (!GETTOKEN()) router.push("/login");
    if (!GETSTUDENT()) router.push("/login");
    user.value = GETSTUDENT();
    if (!GETSTUDENT().hasOwnProperty("description")) user.value["description"] = "";
    if (!GETSTUDENT().hasOwnProperty("image")) user.value["image"] = null;
    image.value = user.value["image"];

    console.log(user.value);
    requestAnalytics();
});
</script>

<style scoped>
.container {

    width: 100%;
    overflow-y: scroll;
    padding: 20px;
    padding-bottom: 120px;
}

.title {
    font-size: 30px;
    font-weight: bold;
}

.card {
    padding: 20px;
    width: 100%;
    margin-top: 20px;
}

.heading {
    font-size: 20px;
    font-weight: 400;
    text-transform: uppercase;
    margin-bottom: 10px;
}


.usertitle {
    font-size: 1.8rem;
    font-weight: bold;
    color: var(--secondary);
    margin-bottom: 10px;
}

.userid {
    font-size: 1.1rem;
    font-weight: 400;
    color: var(--secondary);
    margin-bottom: 10px;
}

.divider {
    display: flex;
    width: 100%;
    gap: 40px;
    justify-content: space-between;
}

.button {
    color: white;
    font-weight: 300;
    width: 160px;
    height: 45px !important;
    background-color: var(--primary);
}

.profile {
    background-color: var(--primary);
    color: white;
    max-width: 120px;
    max-height: 120px;
    min-width: 120px;
    min-height: 120px;
    border-radius: 50%;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 50px;
    overflow: hidden;
}

.imghandler {
    width: 100%;
    height: 100%;

}

.dashboard-divider {
    display: flex;
    flex-direction: row;
    gap: 20px;
}

.divider {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
}

.datacontainer {
    display: flex;
    flex-direction: column;
    gap: 20px;
    align-items: center;
}

.profilecontainer {
    display: flex;
    flex-direction: column;
    gap: 6px;
}

.graphcontainer {
    width: 600px;
    height: 300px;
}

.dashboard-divider {
    display: flex;
    flex-direction: row;
    gap: 20px;
}

.welcome-label {
    width: 100%;
    height: 300px;
    padding: 20px;
    display: flex;
    flex-direction: column;
}

.card2 {
    width: 100%;
    margin-top: 20px;
}

.text {
    font-size: 18px;
    margin-right: 20px;
    margin-top: 10px;
}

.button2 {
    color: white;
    font-weight: 300;
    width: 160px;
    height: 45px !important;
    background-color: var(--primary);
}

.spacer {
    flex: 1;
}
</style>